CREATE TABLE Departement (
        dptNo CHAR(3) PRIMARY KEY NOT NULL,
        dptLib VARCHAR(30) NOT NULL,
        dptMgr CHAR(3) NOT NULL,
        dptAdm CHAR(3)
);
CREATE TABLE Employe (
        empNo CHAR(3) PRIMARY KEY NOT NULL,
        empNom VARCHAR(30) NOT NULL,
        empSal DECIMAL(11,2) NOT NULL,
        empSexe CHAR(1) NOT NULL,
        empDpt CHAR(3) NOT NULL
);
ALTER TABLE Departement 
        ADD CONSTRAINT selfAdminDPT CHECK(dptAdm IS NULL OR dptNo != dptAdm);
ALTER TABLE Departement 
        ADD CONSTRAINT managerDPT FOREIGN KEY(dptMgr) REFERENCES Employe(empNo);
ALTER TABLE Departement 
        ADD CONSTRAINT uniqueManagerDPT UNIQUE(dptMgr);
ALTER TABLE Departement 
        ADD CONSTRAINT uniqueLabelDPT UNIQUE(dptLib);
ALTER TABLE Employe
        ADD CONSTRAINT checkSexe CHECK(empSexe IN('F', 'M'));
alter table Employe
        ADD CONSTRAINT checkSal CHECK(empSal BETWEEN 10000 AND 200000);	

Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('020','DURANT',103961,'M','E21');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('030','SMITH',118916,'M','C01');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('050','GOULD',100812,'M','E11');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('060','ALLEN',110212,'F','C01');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('070','DANOIS',140214,'M','D21');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('090','VAN HE',100215,'F','E11');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('100','HIEL',110311,'M','C01');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('110','KOALA',95311,'M','A00');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('120','Mc CARTNEY',185312,'M','A00');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('130','ALBERT',92351,'M','C01');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('140','LENNON',64241,'M','C01');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('150','STARR',104248,'M','E21');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('160','HARRISSON',84441,'M','D11');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('170','LISA',93468,'F','D11');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('031','LUDI',99999,'M','C01');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('190','LUDI',72665,'M','D11');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('200','VAN BLAER',92665,'M','D11');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('220','DE COO',92665,'M','D11');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('230','DANTE',50665,'M','D21');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('240','MANTE',60666,'F','D21');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('250','DATTA',100665,'M','D21');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('260','MARKA',80665,'M','C01');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('270','PEREZ',110666,'F','D21');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('280','MOZART',18665,'M','E11');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('290','BOURVIL',98665,'M','E11');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('300','DELON',139065,'M','E11');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('310','TOOR',69065,'M','E11');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('320','MAES',99066,'F','E21');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('330','VAN RAES',56066,'F','E21');
Insert into EMPLOYE (EMPNO,EMPNOM,EMPSAL,EMPSEXE,EMPDPT) values ('340','GIELS',86065,'M','E21');

Insert into DEPARTEMENT (DPTNO,DPTLIB,DPTMGR,DPTADM) values ('D21','DIRECTION','070',null);
Insert into DEPARTEMENT (DPTNO,DPTLIB,DPTMGR,DPTADM) values ('A00','DEVELOPPEMENT','320','D21');
Insert into DEPARTEMENT (DPTNO,DPTLIB,DPTMGR,DPTADM) values ('B01','PRODUCTION','020','A00');
Insert into DEPARTEMENT (DPTNO,DPTLIB,DPTMGR,DPTADM) values ('C01','MAINTENANCE','030','A00');
Insert into DEPARTEMENT (DPTNO,DPTLIB,DPTMGR,DPTADM) values ('E11','VENTES','340','D21');
Insert into DEPARTEMENT (DPTNO,DPTLIB,DPTMGR,DPTADM) values ('D11','SUPPORT','060','E11');
Insert into DEPARTEMENT (DPTNO,DPTLIB,DPTMGR,DPTADM) values ('E01','MARKETING','050','E11');
Insert into DEPARTEMENT (DPTNO,DPTLIB,DPTMGR,DPTADM) values ('E21','FORMATION','100','E11');

